# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53eedd6b1e64b381f478aa397a8b94a8ae3ec5dd49503f08960e5f2ed749cda1a363dabd0463d2cc2fd4b7d06d88160624cd5b5daa6d8e916468b689c24c81a9

test:
  secret_key_base: bde5ddde9d8140027d85db087ba45b5ed44793b1e770f0d23f8168d92b2b2a43efdb48230795ce883d9e9e3366f24e5a67059bfcee25a0e54acad0561bdad1a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
